"""Update_Users

Revision ID: c01ca46701f2
Revises: fb8d7fac5884
Create Date: 2023-05-17 09:24:29.228090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01ca46701f2'
down_revision = 'fb8d7fac5884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'config')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
