#alembic init alembic
        # chưa có table dữ liệu trong database
#alembic revision --autogenerate -m "First revision"
#alembic upgrade head

# alembic revision --autogenerate -m "Update_Users"

#alembic upgrade c01ca  -- để nâng cấp lên

#alembic downgrade -1   -- hạ 1 cấp xuống





"""First revision

Revision ID: fb8d7fac5884
Revises: 
Create Date: 2023-05-17 09:11:20.751514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8d7fac5884'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('sub', sa.String(), nullable=False),
    sa.Column('last_requested_time', sa.String(), nullable=True),
    sa.Column('email_verified', sa.String(), nullable=True),
    sa.Column('phone_number_verified', sa.String(), nullable=True),
    sa.Column('old_sub', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('nd_requests', sa.String(), nullable=True),
    sa.Column('nm_requests', sa.String(), nullable=True),
    sa.Column('app_key', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created', sa.String(), nullable=True),
    sa.Column('updated', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sub')
    )
    op.create_index(op.f('ix_users_sub'), 'users', ['sub'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sub'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
